version: "3.8"

services:
  dmm:
    image: docker
    entrypoint: docker
    command: |
      run 
      -i
      --name device-manager 
      --restart always 
      --privileged 
      --cgroupns=host 
      --pid=host 
      --userns=host 
      -v /sys:/host/sys 
      -v /var/run/docker.sock:/var/run/docker.sock 
      -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      ghcr.io/mels0n/device-mapping-manager:master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
